# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'plai' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for plai
  platform :ios, '9.0'
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'


  target 'plaiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'plai-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for plai-tvOS

  target 'plai-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
