# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'plai' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for plai
  platform :ios, '9.0'
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Google/SignIn'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'plaiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'plai-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for plai-tvOS

  target 'plai-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
